services:
  driver:
    image: ghcr.io/restatedev/e2e-node-services
    ports:
      - 3000:3000
    depends_on:
      interpreter:
        condition: service_started
      restate:
        condition: service_started
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=4096"
      SERVICES: InterpreterDriverJob
      INTERPRETER_DRIVER_CONF: ${INTERPRETER_DRIVER_CONF}
    restart: "no"
  interpreter:
    image: ghcr.io/restatedev/e2e-node-services
    ports:
      - 9080:9080
    environment:
      - RESET_LOGGING=INFO
      - NODE_ENV=production
      - SERVICES=ObjectInterpreterL0,ObjectInterpreterL1,ObjectInterpreterL2,ServiceInterpreterHelper
    restart: always
  restate:
    image: ghcr.io/restatedev/restate:main
    ports:
      - 8080:8080
      - 9090:9090
      - 9070:9070
      - 8081:8081
    restart: "no"
    environment:
      - RESTATE_LOG_FILTER=restate=warn
      - RESTATE_LOG_FORMAT=json
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
