name: Verification tests

on:
  workflow_dispatch: # To start from UI
  schedule:
    - cron: "12 0 * * *" # 00:12am UTC daily

env:
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  GHCR_REGISTRY: "ghcr.io"
  GHCR_REGISTRY_USERNAME: ${{ github.actor }}
  GHCR_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    # prevent running on forks
    if: github.repository_owner == 'restatedev'
    runs-on: warp-ubuntu-latest-x64-16x # warpbuild runner
    timeout-minutes: 250 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ env.GHCR_REGISTRY_USERNAME }}
          password: ${{ env.GHCR_REGISTRY_TOKEN }}

      - run: ./run.sh
        working-directory: services/node-services
